function job = new_job(varargin)
%NEW_JOB Create a queue job template for one (B, T) point.
%
% Usage:
%   job = v3_1.new_job();
%   job = v3_1.new_job('id','job_001','name','B0T0','B',100,'T',300);

opts = parse_name_value(varargin{:});
job = struct();

if isfield(opts, 'id') && ~isempty(opts.id)
    job.id = char(opts.id);
else
    job.id = sprintf('job_%s_%04d', datestr(now, 'yyyymmdd_HHMMSS'), randi([0, 9999]));
end

if isfield(opts, 'name') && ~isempty(opts.name)
    job.name = char(opts.name);
else
    job.name = 'Unnamed Job';
end

job.enabled = true;
job.order = 1;

bSet = 0;
tSet = 0;
if isfield(opts, 'B'), bSet = opts.B; end
if isfield(opts, 'T'), tSet = opts.T; end
job.setpoint = struct('B', bSet, 'T', tSet);

job.profile = struct( ...
    'name', 'snapshot', ...
    'snapshot', struct(), ...
    'revision', 1, ...
    'updatedAt', datestr(now, 'yyyy-mm-dd HH:MM:SS.FFF') ...
);

job.runtime = struct( ...
    'retry', struct('maxAttempts', 1, 'policy', 'skip_job'), ...
    'timeout', struct('settleSec', 30) ...
);

job.status = struct( ...
    'state', 'pending', ...                 % pending | running | success | failed | skipped | stopped
    'attemptCount', 0, ...
    'userDeclaredFailed', false, ...
    'userFailAction', 'none', ...           % none | skip | redo
    'lastResult', '', ...
    'lastTimestamp', '' ...
);

job.history = repmat(struct( ...
    'attemptIdx', 0, ...
    'startedAt', '', ...
    'endedAt', '', ...
    'outcome', '', ...
    'errorMessage', '', ...
    'runFolder', '', ...
    'sequenceRows', repmat(struct( ...
        'sequenceName', '', ...
        'date', '', ...
        'aveFigureName', '', ...
        'figurePath', ''), 0, 1) ...
), 0, 1);
end

function opts = parse_name_value(varargin)
opts = struct();
if mod(nargin, 2) ~= 0
    error('SmartT1:v3_1:InvalidArgs', 'Name/value arguments must be paired.');
end
for i = 1:2:nargin
    key = varargin{i};
    if ~(ischar(key) || isstring(key))
        error('SmartT1:v3_1:InvalidArgs', 'Option names must be text.');
    end
    opts.(char(key)) = varargin{i + 1};
end
end
