function cfg = AutoPipelineConfig()
% Central configuration for T1 semi-auto orchestration.
%
% Primary knobs for future experiments:
% 1) cfg.stepOrder         -> choose which sequence runs and in what order
% 2) cfg.steps.<StepId>    -> parameter sources/constants/derived values
% 3) cfg.steps.<StepId>.fitFunction -> post-run fit hook function name
% 4) cfg.plotting          -> per-sequence live plotting behavior in T1_SemiAuto_Run
% 5) cfg.outerAutomation   -> optional (T, B) schedule loop above the inner flow

cfg = struct();

% Edit this list to reorder/disable/insert steps.
cfg.stepOrder = {'Presets', 'ESR', 'Rabi', 'ESR2', 'Rabi2', 'T00', 'T11'};

cfg.paths.saveFolder = 'C:\Users\dilution_fridge_2\Desktop\T1_SemiAuto_Saves';
cfg.paths.slackScriptFolder = fileparts(mfilename('fullpath'));
cfg.slack.defaultKeep = 100;

% Live plotting behavior during T1_SemiAuto_Run:
% - maxCtrToPlot: skip plotting when counter-gate number is too large.
% - rules: {sequenceName, plotFunction, liveFitFunction}
%   liveFitFunction can be '' if no per-iteration fit is needed.
cfg.plotting = struct();
cfg.plotting.maxCtrToPlot = 24;
cfg.plotting.default = struct( ...
    'plotFunction', 'PlotData', ...
    'liveFitFunction', '');
cfg.plotting.rules = { ...
    'Rabi', 'PlotRabiData', 'FitRabi'; ...
    'Rabi_SG2', 'PlotRabiData', 'FitRabi'; ...
    'T1_S00_S01_S10_S11_S1m1', 'PlotT1Data_method2', ''; ...
    'T1_S11_S1m1', 'PlotT1Data_method3', ''; ...
    'T1_S00_S01_S10', 'PlotT1Data_method4', ''; ...
    'T1_S00_S01_S10_S11_darkRef', 'PlotT1Data', '' ...
};

% Outer automation loop: for each setpoint -> set T, set B, run inner flow.
% Keep disabled until device-control hooks are ready for production use.
cfg.outerAutomation = struct();
cfg.outerAutomation.enabled = false;
cfg.outerAutomation.temperatureHook = 'set_temperature';
cfg.outerAutomation.magneticFieldHook = 'set_magnetic_fields';
cfg.outerAutomation.allowMissingHooks = true;
cfg.outerAutomation.stopOnSetpointError = true;
cfg.outerAutomation.pauseAfterSetpointSec = 0;
cfg.outerAutomation.autoPrefixFigureTitle = true;
cfg.outerAutomation.schedule = [ ...
    make_setpoint(4.0, [0 0 100], 'T4p0_B100', 0) ...
];

cfg.steps = struct();

cfg.steps.Presets = struct( ...
    'kind', 'preset', ...
    'fitFunction', '');

cfg.steps.PulsedESR1 = struct( ...
    'kind', 'generic', ...
    'sequenceName', 'ODMR', ...
    'uiStringMap', {{ ...
        'FROM1', 'startESR'; ...
        'TO1', 'stopESR'; ...
        'SweepNPoints', 'nPtsESR'; ...
        'fixPow', 'MWPowerESR'; ...
        'Repeat', 'RepeatESR'; ...
        'Average', 'maxAveESR' ...
    }}, ...
    'constantValues', struct('useSG2', 0, 'bSweep2', 0), ...
    'derivedValues', struct(), ...
    'fitFunction', 'FitESR');

cfg.steps.Rabi = struct( ...
    'kind', 'generic', ...
    'sequenceName', 'Rabi', ...
    'uiStringMap', {{ ...
        'FROM1', 'startRabi'; ...
        'TO1', 'stopRabi'; ...
        'SweepNPoints', 'nPtsRabi'; ...
        'fixPow', 'MWPowerRabi'; ...
        'Repeat', 'RepeatRabi'; ...
        'Average', 'maxAveRabi' ...
    }}, ...
    'constantValues', struct('useSG2', 0), ...
    'derivedValues', struct('fixFreq', 'gmSEQ.ESRFitFreq_GHz'), ...
    'fitFunction', 'FitRabi');

cfg.steps.PulsedESR2 = struct( ...
    'kind', 'generic', ...
    'sequenceName', 'ODMR', ...
    'uiStringMap', {{ ...
        'FROM1', 'startESR2'; ...
        'TO1', 'stopESR2'; ...
        'SweepNPoints', 'nPtsESR2'; ...
        'fixPow', 'MWPowerESR2'; ...
        'Repeat', 'RepeatESR2'; ...
        'Average', 'maxAveESR2' ...
    }}, ...
    'constantValues', struct('useSG2', 0), ...
    'derivedValues', struct('pi', 'gmSEQ.RabiFitPi_ns'), ...
    'fitFunction', 'FitESR');

cfg.steps.Rabi2 = struct( ...
    'kind', 'generic', ...
    'sequenceName', 'Rabi_SG2', ...
    'uiStringMap', {{ ...
        'FROM1', 'startRabi2'; ...
        'TO1', 'stopRabi2'; ...
        'SweepNPoints', 'nPtsRabi2'; ...
        'fixPow2', 'MWPowerRabi2'; ...
        'Repeat', 'RepeatRabi2'; ...
        'Average', 'maxAveRabi2' ...
    }}, ...
    'constantValues', struct('useSG2', 1), ...
    'derivedValues', struct('fixFreq2', 'gmSEQ.ESRFitFreq_GHz'), ...
    'fitFunction', 'FitRabi');

cfg.steps.T00 = struct( ...
    'kind', 'custom', ...
    'customBuilder', 'build_step_t00', ...
    'fitFunction', '');

cfg.steps.T11 = struct( ...
    'kind', 'custom', ...
    'customBuilder', 'build_step_t11', ...
    'fitFunction', '');

end

function sp = make_setpoint(temperature, magneticField, label, settleSec)
sp = struct();
sp.temperature = temperature;
sp.magneticField = magneticField;
sp.label = label;
sp.settleSec = settleSec;
end
