/*  \file     C4Device.hpp
 *  \brief    C++ Library for access to heliotis GenICam based camera C4
 *  \version  0.0.1
 *  \author   Silvan Murer, heliotis
 *  \date     2019
 */

#ifndef INC_C4DEVICE
#define INC_C4DEVICE

#include "C4HdlDef.hpp"
#include "C4FeatureInfo.hpp"
#include "C4Buffer.hpp"

#include <stdint.h>
#include <string>
#include <vector>

namespace heliotis {

class DeviceComponent;

/**
 * Class to the C4Device
 *
 * This class is used for device access.
 * It configure the C4 device and acquire data from it.
 * Data are transfered through a C4Buffer object.
 */
class C4LIB_API C4Device {
private:
  DeviceComponent* c4DeviceComponent; /**< pointer to internal data */
  /**
   * \brief no default constructor is available for this class
   */
  C4Device();

public:
  /**
   * \brief constructor to create a C4Device instance
   *
   * Don't create a C4Device by self. Use the C4Interface::openDevice function!
   */
  C4Device(void* devH, void* c4ActiveDevH);

  /**
   * \brief copy constructor
   */
  C4Device(const C4Device& other);
  /**
   * \brief copy assignment not supported by this class
   */
  C4Device& operator=(const C4Device& other) = delete;

  /**
   * \brief move constructor
   */
  C4Device(C4Device && other);
  /**
   * \brief move assignment not supported by this class
   */
  C4Device& operator=(C4Device && other) = delete;

  /**
   * \brief destructor
   */
  ~C4Device();

  /**
   * \brief function to release a device.
   *
   * A call to this function release all allocated memory and C4Buffers generated by this device.
   */
  void release();
  /**
   * \brief read the device name
   *
   * \return a string value including the device name
   */
  std::string getDeviceName();

  /**
   * \brief get a list with all available device features
   *
   * \return a vector containing C4FeatureInfo objects
   */
  std::vector<C4FeatureInfo> getFeatureList();
  /**
   * \brief get the type of a specific feature
   *
   * \return the type of a specific feature
   */
  C4FeatureInfo::Type_e getFeatureType(std::string name);

  /* device feature access */
  /**
   * \brief get value of an integer feature
   *
   * \param[in]     name    feature name
   *
   * \return integer feature value
   */
  int64_t readInteger(std::string name);
  /**
   * \brief set value of an integer feature
   *
   * \param[in]     name    feature name
   * \param[in]     value   new feature value
   */
  void writeInteger(std::string name, int64_t value);
  
  /**
   * \brief get value of an float feature
   *
   * \param[in]     name    feature name
   *
   * \return float feature value
   */
  double readFloat(std::string name);
  /**
   * \brief set value of an float feature
   *
   * \param[in]     name    feature name
   * \param[in]     value   new feature value
   */
  void writeFloat(std::string name, double value);

  /**
   * \brief get value of an string feature
   *
   * \param[in]     name    feature name
   *
   * \return string feature value
   */
  std::string readString(std::string name);
  /**
   * \brief set value of an string feature
   *
   * \param[in]     name    feature name
   * \param[in]     value   new feature value
   */
  void writeString(std::string name, std::string value);

  /**
   * \brief get value of an enumeration feature
   *
   * \param[in]     name    feature name
   *
   * \return enumeration feature value as string
   */
  std::string readEnumeration(std::string name);
  /**
   * \brief set value of an enumeration feature
   *
   * \param[in]     name    feature name
   * \param[in]     value   new feature value
   */
  void writeEnumeration(std::string name, std::string value);

  /**
   * \brief execute a command feature
   *
   * \param[in]     name    feature name
   */
  void executeCommand(std::string name);

  /**
   * \brief read the file given in fileSelector from the device and store it in localFile
   *
   * \param[in]     fileSelector    device file (FileSelector) which should be readed from the device
   * \param[in]     localFile       local file (path and name) where the file from the device is stored
   */
  void readFile(std::string fileSelector, std::string localFile);
  /**
   * \brief write a file to the device and store it as file selected in fileSelector
   *
   * \param[in]     fileSelector    device file (FileSelector) which should be replaced on the device
   * \param[in]     localFile       local file (path and name) which is written to the device
   */
  void writeFile(std::string fileSelector, std::string localFile);

  /* device state configuration */
  /**
   * \brief switch to acquisition state
   */
  void startAcquisition(int64_t nofBuf);
  /**
   * \brief switch to acquisition stop / configuration state
   */
  void stopAcquisition();

  /**
   * \brief get the next buffer object containig measurement data
   */
  C4Buffer getBuffer(int64_t timeout_ms);

  /**
   * \brief register an event feature to the event engine
   * 
   * \param[in]     name    feature name
   */
  void registerEvent(std::string name);
  /**
   * \brief unregister an event feature from the event engine
   *
   * \param[in]     name    feature name
   */
  void unregisterEvent(std::string name);
  /**
   * \brief blocking wait for a bevore registered event.
   *
   * \param[in]     timeout_ms    timeout of calling function
   * 
   * \return a list of strings containing the features which triggerd an event
   */
  std::vector<std::string> waitForEvents(int64_t timeout_ms);

};

} /* namespace heliotis */

#endif
