function status = DAQmxCreateAIVoltageChan(taskHandle, physicalChannel, ...
    nameToAssignToChannel, terminalConfig, minVal, maxVal,...
    units, customScaleName)


status = calllib('mynidaqmx','DAQmxCreateAIVoltageChan',taskHandle, physicalChannel, ...
    nameToAssignToChannel, terminalConfig, minVal, maxVal, units, customScaleName);
