function [status, readArray, sampsPerChanRead]=DAQmxReadCounterU32(taskHandle, numSampsPerChan,...
    timeout, readArray, arraySizeInSamps, sampsPerChanRead )

[status,readArray, sampsPerChanRead]=calllib('mynidaqmx','DAQmxReadCounterU32',taskHandle, numSampsPerChan, ...
    timeout, readArray, arraySizeInSamps, sampsPerChanRead,[]);