function [status, readArray]=DAQmxReadCounterF64(taskHandle, numSampsPerChan,...
    timeout, readArray, arraySizeInSamps, sampsPerChanRead )

[status,readArray]=calllib('mynidaqmx','DAQmxReadCounterF64',taskHandle, numSampsPerChan, ...
    timeout, readArray, arraySizeInSamps, sampsPerChanRead,[]);