function [status] = DAQmxCreateCIPulseWidthChan(taskHandle, strCounter,...
    strNameToAssignToChannel, minVal, maxVal, units, startingEdge, strCustomScaleName);

[status] = calllib('mynidaqmx','DAQmxCreateCIPulseWidthChan',taskHandle, strCounter,...
    strNameToAssignToChannel, minVal, maxVal, units, startingEdge, strCustomScaleName);