function [status] = DAQmxCfgSampClkTiming(task,source,rate,...
    activeEdge,sampleMode,sampsPerChanToAcquire)

status = calllib('mynidaqmx','DAQmxCfgSampClkTiming',...
    task,source,rate,activeEdge,sampleMode,sampsPerChanToAcquire);