function status = DAQmxCreateCOPulseChanFreq(taskHandle, counter, nameToAssignToChannel,...
    units, idleState, initialDelay, freq, dutyCycle)

[status] = calllib('mynidaqmx','DAQmxCreateCOPulseChanFreq',taskHandle, counter, nameToAssignToChannel,...
    units, idleState, initialDelay, freq, dutyCycle);