function [status] = DAQmxWriteDigitalU32(taskHandle, numSampsPerChan,...
    bAutoStart, timeout, bDataLayout, writeArray, sampsPerChanWritten)

[status] = calllib('mynidaqmx','DAQmxWriteDigitalU32',taskHandle, numSampsPerChan,...
    bAutoStart, timeout, bDataLayout, writeArray, sampsPerChanWritten,[]);