function unloadNI
%UNLOADNI calls loadlibrary with the appropriate input arguments.
%
% This function will call unloadlibrary on the library defined as NI
%
% You must have cleared memory and not have any varables defined using 
%	this library to work.
%
% This file is automatically generated by the loadlibrarygui.
%
%   See also
%   LOADLIBRARY, UNLOADLIBRARY, LOADNI

%
%
% $Author: $
% $Revision: $
% $Date: 12-Feb-2004 10:05:04 $
%
% Local Functions Defined:
%
%
% $Notes:
%
%
%
%
% $EndNotes
%
% $Description:
%
%
%
%
% $EndDescription
% unload the library.
if libisloaded('NI');
	unloadlibrary('NI');
end
